### ISSUE TITLE
PCB mounting files

### ISSUE THREAD

**Issue by nrayner** [borti4938/n64adv2_pcb#1]
In the readme it says:

If you want to use a assembly service (PCBA), you can use the mounting files for [main](https://github.com/borti4938/n64adv2_pcb/blob/master/doc/n64adv2-top-pos.csv), full flex-PCB and/or part flex-PCB, too.

But the link doesn't work, I could not find the files anywhere else in the repository.

**Comment by borti4938** [comment]
Sorry. I removed the file as it was not working for any fab. At the moment you have to generate your own files in a format as requested by the fab of your choice. Maybe we will add some example files for JLCPCB in near future.

I edited the README to avoid confusion.

**Comment by nrayner** [comment]
Ok thanks
