### ISSUE TITLE
Alternativ FPGA?

### ISSUE THREAD

**Issue by cerritus55** [borti4938/n64adv2_pcb#2]
Is there any alternativ for the FPGA thats still aviable and working with this project?

**Comment by borti4938** [comment]
New FPGA needs a redesign of PCB and firmware. Everything is open source, so feel free to make your adaptations. Or just be patient - FPGAs will be available soon. Estimated delivery date at Digikey is 01/17/2024 (10M16SAE144) or 01/12/2024 (10M25SAE144) if you order today.
