### ISSUE TITLE
Interference 

### ISSUE THREAD

**Issue by Slypty** [borti4938/n64adv2_pcb#3]
I've made a set of 8 N64Adv2 boards with PCBWay, received them and doing some testing.  2 of the 8 boards test well, the other 6 all have blue pixels that appear.  The pixels will go away if I press down between the FPGA MAX 10 and the Alliance IC as shown below.  I have tried touching up solder joints in this area but no differences were made. 

  If I add thermal tape to the underside of the PCB it gets better.  Eventually the pixels go away after many minutes.  6 boards all have this issue, I am wondering if I should replace the caps in this area, or maybe if this is a noisy 3.3V line?  Is this a problem you're familiar with?   Hope you can help, thanks
![badspot](https://github.com/borti4938/n64adv2_pcb/assets/50507968/4df30e32-9efa-4c96-aff3-63927fa18a46)

**Comment by Slypty** [comment]
Well it ended up being a faulty N64 Power Supply, so it can be deleted/closed.

**Comment by borti4938** [comment]
Thanks for closing. I'm happy that you were able to track down the issue :)
