### ISSUE TITLE
SDRAM alternative part

### ISSUE THREAD

**Issue by gmiranda** [borti4938/n64adv2_pcb#4]
Hi,

I'm having trouble sourcing the alliance SDRAM chip (AS4C8M16SA) and I'm looking into alternatives. I think this Winbond W9812G6KH ([datasheet](https://www.lcsc.com/datasheet/lcsc_datasheet_2304140030_Winbond-Elec-W9812G6KH-6_C62379.pdf)) would work but I'm not sure.

Could you please have a look or suggest another IC?

Thanks!

**Comment by borti4938** [comment]
Hi,

the AS4C8M16SA-7TCN is available on Digikey and Mouser on high quantities at least. So it should be a problem to source the SDRAM.

For the W9812G6KH you have to go for speed rating -5 or -6. Then it should work. However, no guarantee on that as I just shortly scanned over pinout, commands and AC characteristics. But you may want to provide feedback, once tested. If you go for the chip with speed rate -75, you may have to adjust clock rate (143MHz to 133MHz), tRC (63ns -> 65ns) and tRAS (42ns -> 45ns). Otherwise it might be a bit of luck whether it works with current firmware or not.

Best regards

**Comment by gmiranda** [comment]
Hi borti,

Thanks a lot for replying. I was planning on avoiding Mouser and instead go to LCSC, but now I see that I'd have to use a lot of alternative parts.

That said, I'm still having some trouble sourcing a couple of components. The first one would be U7, 74LVC2G17DBV. The closest one I can find on either Mouser or DigiKey is 74LVC2G17DBV**R**. Is it the same thing?

I also have doubts regarding the flex pcb, I hope you don't mind me asking. Have you ever ordered from JLCPCB? I don't know what to select on **Gold fingers**. Options are _yes_/_no_ and then it asks me about the gold finger thickness which puts me at a loss.

Thanks a lot!

**Comment by borti4938** [comment]
Not sure, if you are using the latest version. Last version has no U7. For the flex, you have to select "yes" for gold fingers (pins at the end for the connector).

**Comment by borti4938** [comment]
These are the options I set on my last order for the flex pcb. Works well
![Screenshot 2024-09-02 195918](https://github.com/user-attachments/assets/2041e318-b59c-42e7-8ee7-290fb19c7f9b)

**Comment by gmiranda** [comment]
> Not sure, if you are using the latest version. Last version has no U7. For the flex, you have to select "yes" for gold fingers (pins at the end for the connector).

It looks like I wasn't, thanks!

> These are the options I set on my last order for the flex pcb. Works well !

Awesome borti, thanks a lot! It looks like I had the values miraculously right.

**Comment by gmiranda** [comment]
I'm now going through the flex pcb BOM and I'm having a similar issue with U1 as I did with former U7. Searching for 74LVC1G17DBV returns quite 6 different part numbers with the closest ones being SN74LVC1G17DBVR and SN74LVC1G17DBVT. Which one should I order?

**Comment by borti4938** [comment]
You can go with either one. "SN" is probably for Texas Instrument and "R"/"T" is just the packaging the device comes (reel or tube), which is not important at all. Take the cheaper version.

**Comment by gmiranda** [comment]
Sorry to keep bothering you... Are the pads of the clamps D21 and D22 intended to be electrically connected? I mean that with the bare PCB there's connection between the north side (HDMI connector) and the south side (analog devices chip) pads:

![image](https://github.com/user-attachments/assets/f648cd5c-5f14-4d1d-bd78-5f81d9bb2b30)

This lead me to believe that I had botched the solder work of these diodes :facepalm: 

Once again, thanks a lot!

**Comment by gmiranda** [comment]
I guess the answer is yes. I just don't understand how these clamps work.
